In [1]:
import torch
from torch.nn import Module, Linear

In [2]:
class TestModel(Module):
    def __init__(self):
        super(TestModel, self).__init__()
        self.fc = Linear(10, 1)

    def forward(self, x):
        return self.fc(x)

In [3]:
device = "cuda"

In [4]:
test_model = TestModel()
test_model.to(device)

TestModel(
  (fc): Linear(in_features=10, out_features=1, bias=True)
)

In [5]:
optim = torch.optim.Adam(test_model.parameters(), lr=0.01)

g:\Projects\ML\PreDAT2\.venv\lib\site-packages\transformers\utils\hub.py:124: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(


In [6]:
torch.save(
    {
        "model": test_model.state_dict(),
        "optim": optim.state_dict()
    },
    "test_model.pth"
)

In [9]:
list(test_model.parameters())

[Parameter containing:
 tensor([[-0.2842, -0.1088,  0.1678, -0.2566,  0.1929,  0.3151, -0.1473,  0.1822,
           0.0162,  0.2894]], device='cuda:0', requires_grad=True),
 Parameter containing:
 tensor([0.1748], device='cuda:0', requires_grad=True)]

In [10]:
checkpoint = torch.load("test_model.pth")

In [11]:
loaded_model = TestModel()

In [12]:
loaded_model.load_state_dict(checkpoint["model"])

<All keys matched successfully>

In [13]:
loaded_optim = torch.optim.Adam(loaded_model.parameters())
loaded_optim.load_state_dict(checkpoint["optim"])

In [14]:
list(loaded_model.parameters())

[Parameter containing:
 tensor([[-0.2842, -0.1088,  0.1678, -0.2566,  0.1929,  0.3151, -0.1473,  0.1822,
           0.0162,  0.2894]], requires_grad=True),
 Parameter containing:
 tensor([0.1748], requires_grad=True)]