In [11]:
import torch
from torch.nn import Embedding

In [12]:
vocab_size = 4
emb_dim = 2
emb = Embedding(vocab_size, emb_dim)

In [13]:
batch_size = 2
seq_len = 5
x = torch.randint(0, vocab_size, (batch_size, seq_len))

In [14]:
pos_emb = Embedding(seq_len, emb_dim)

In [15]:
b,t = x.shape

In [16]:
pos_x =  torch.arange(t).unsqueeze(0)

In [17]:
pos_embedding = pos_emb(pos_x)

In [18]:
vocab_embedding = emb(x)

In [20]:
pos_embedding

tensor([[[ 0.7212,  0.9661],
         [ 1.3569,  0.0583],
         [ 0.1616, -0.9982],
         [ 0.0037,  3.3588],
         [ 0.0337,  0.4048]]], grad_fn=<EmbeddingBackward0>)

In [21]:
vocab_embedding

tensor([[[-0.0031, -0.4813],
         [-0.3123,  0.2890],
         [ 0.5745, -0.9526],
         [ 0.5745, -0.9526],
         [-0.0764, -0.3512]],

        [[-0.3123,  0.2890],
         [-0.3123,  0.2890],
         [-0.3123,  0.2890],
         [-0.0031, -0.4813],
         [ 0.5745, -0.9526]]], grad_fn=<EmbeddingBackward0>)

In [23]:
combined = vocab_embedding + pos_embedding

In [24]:
vocab_embedding[1][2][0] + pos_embedding[0][2][0]

tensor(-0.1507, grad_fn=<AddBackward0>)

In [25]:
combined[1][2][0]

tensor(-0.1507, grad_fn=<SelectBackward0>)

In [26]:
combined

tensor([[[ 7.1803e-01,  4.8484e-01],
         [ 1.0446e+00,  3.4727e-01],
         [ 7.3607e-01, -1.9508e+00],
         [ 5.7823e-01,  2.4062e+00],
         [-4.2679e-02,  5.3587e-02]],

        [[ 4.0885e-01,  1.2551e+00],
         [ 1.0446e+00,  3.4727e-01],
         [-1.5072e-01, -7.0919e-01],
         [ 6.1761e-04,  2.8775e+00],
         [ 6.0819e-01, -5.4777e-01]]], grad_fn=<AddBackward0>)